server:
  port: 9010

housekeepingbook:
  admin:
    name: admin
    password: secret
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/housekeepingbook
    username: postgres
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
